const crypto = require('crypto')
const fs = require('fs')
const path = require('path')
const os = require('os')
const { verifyLicenseSignature } = require('./license_signing')

// ── Ed25519 verification (the target scheme) ────────────────────────────────
// Licenses issued by server/ carry a `sig` over the canonical fields; the app
// verifies it with this bundled PUBLIC key (generated by server/keygen.js).
// The private key never ships, so a signed license cannot be forged from
// anything inside the app.
const PUBLIC_KEY_FILE = path.join(__dirname, 'license_public_key.pem')
let PUBLIC_KEY = null
try { PUBLIC_KEY = fs.readFileSync(PUBLIC_KEY_FILE, 'utf8') } catch (_) { /* not generated yet */ }

// ── Legacy HMAC checksum ─────────────────────────────────────────────────────
// Kept ONLY so licenses saved by older builds keep working; the shared secret
// ships with the app and is forgeable by construction. Signed licenses (sig)
// always take precedence, and new saves keep whichever proof they carry.
const SECRET_KEY = process.env.LICENSE_SECRET_KEY || 'CH-TOOLKIT-PRO-2025-SECRET'
if (!process.env.LICENSE_SECRET_KEY) {
  console.warn('[license] WARNING: LICENSE_SECRET_KEY not set — using insecure fallback. Set it in .env before distributing.')
}
const LICENSE_FILE = path.join(os.homedir(), '.ch_toolkit_license')

function generateChecksum(data) {
  return crypto.createHmac('sha256', SECRET_KEY).update(JSON.stringify(data)).digest('hex')
}

function saveLicense(licenseData) {
  const data = {
    email: licenseData.email,
    name: licenseData.name,
    machineId: licenseData.machineId,
    expiresOn: licenseData.expiresOn,
    activatedOn: licenseData.activatedOn,
    savedAt: new Date().toISOString()
  }
  const checksum = generateChecksum(data)
  // A server-issued signature travels with the license; the checksum keeps
  // older builds able to read the same file.
  const payload = licenseData.sig ? { ...data, sig: licenseData.sig, checksum } : { ...data, checksum }
  fs.writeFileSync(LICENSE_FILE, JSON.stringify(payload), 'utf8')
}

function loadLicense() {
  try {
    if (!fs.existsSync(LICENSE_FILE)) return null
    const payload = JSON.parse(fs.readFileSync(LICENSE_FILE, 'utf8'))
    const { checksum, ...data } = payload

    // Signed license: the Ed25519 signature is the proof — the forgeable
    // checksum is ignored when a sig is present.
    if (data.sig) {
      if (!PUBLIC_KEY) {
        console.log('License is signed but no public key is bundled!')
        return null
      }
      const { sig, ...fields } = data
      if (!verifyLicenseSignature(fields, sig, PUBLIC_KEY)) {
        console.log('License signature invalid!')
        return null
      }
      return data
    }

    // Legacy license: HMAC checksum.
    const expectedChecksum = generateChecksum(data)
    if (checksum !== expectedChecksum) {
      console.log('License tampered!')
      return null
    }
    return data
  } catch(e) { return null }
}

function getDaysRemaining(expiresOn) {
  const expiry = new Date(expiresOn)
  const now = new Date()
  const ms = expiry - now
  if (ms <= 0) return 0          // already expired — never report a phantom day
  return Math.floor(ms / (1000 * 60 * 60 * 24))
}

function clearLicense() {
  try { fs.unlinkSync(LICENSE_FILE) } catch(e) {}
}

// Single source of truth for offline license validation. Used by both the
// boot auto-login path and the check-license offline fallback so the rules
// (account match, machine lock, expiry) can never drift apart (R2).
//   - currentMachineId: the machine id of this device
//   - email: optional; when provided, the saved license must belong to it
// Returns the same { allowed, reason, ... } shape as check-license.
function validateOfflineLicense(currentMachineId, email) {
  const localLicense = loadLicense()
  if (!localLicense) {
    return { allowed: false, reason: 'no_internet' }
  }
  if (email && localLicense.email !== email) {
    return { allowed: false, reason: 'wrong_account' }
  }
  if (localLicense.machineId !== currentMachineId) {
    return { allowed: false, reason: 'wrong_machine' }
  }
  const daysLeft = getDaysRemaining(localLicense.expiresOn)
  if (daysLeft <= 0) {
    clearLicense()
    return { allowed: false, reason: 'expired' }
  }
  return { allowed: true, daysLeft, offline: true, email: localLicense.email }
}

module.exports = { saveLicense, loadLicense, getDaysRemaining, clearLicense, validateOfflineLicense }
