/* ============================================================
   ui_folders.js — Collapsible folder-structure panels (G1)
   ------------------------------------------------------------
   Every tab with a folder list uses `.folder-rail > .folder-rail__panel
   > .folder-rail__header`. The collapse chevron is part of the header
   markup (static in index.html + regenerated by getPanelHeaderHTML, so it
   survives folder re-renders). This module:
     - restores each rail's persisted collapsed state on load,
     - injects a chevron into any header that somehow lacks one,
     - handles clicks via delegation (works after any re-render).

   The collapsed STATE lives as `.is-folders-collapsed` on the OUTER
   `.folder-rail` (which is never regenerated), and the chevron glyph is
   driven purely by CSS — so nothing here needs to run again after a
   header is rebuilt.
   ============================================================ */

(function () {
  'use strict'

  const KEY_PREFIX = 'adt_folders_collapsed_'

  function keyFor(rail) {
    return KEY_PREFIX + (rail.id || 'rail')
  }

  function ensureChevron(header) {
    if (!header || header.querySelector('.folder-rail__collapse')) return
    const btn = document.createElement('button')
    btn.className = 'folder-rail__collapse'
    btn.type = 'button'
    btn.setAttribute('aria-label', 'Toggle folder list')
    header.insertBefore(btn, header.firstChild)
  }

  function restore() {
    document.querySelectorAll('.folder-rail').forEach((rail) => {
      const header = rail.querySelector('.folder-rail__header')
      ensureChevron(header)
      let collapsed = false
      try { collapsed = localStorage.getItem(keyFor(rail)) === '1' } catch (_) {}
      rail.classList.toggle('is-folders-collapsed', collapsed)
    })
  }

  function init() {
    restore()
    // Delegated toggle — survives header re-renders (getPanelHeaderHTML).
    document.addEventListener('click', (e) => {
      const btn = e.target.closest('.folder-rail__collapse')
      if (!btn) return
      e.stopPropagation()
      const rail = btn.closest('.folder-rail')
      if (!rail) return
      const collapsed = rail.classList.toggle('is-folders-collapsed')
      try { localStorage.setItem(keyFor(rail), collapsed ? '1' : '0') } catch (_) {}
      window.dispatchEvent(new Event('resize'))
    })
  }

  if (document.readyState === 'loading') {
    document.addEventListener('DOMContentLoaded', init)
  } else {
    init()
  }
})()
